import { defineConfig } from 'unocss'
import transformerDirectives from '@unocss/transformer-directives'
import transformerVariantGroup from '@unocss/transformer-variant-group'
import { generateUnoThemeColors, generateUnoThemeTokens } from './src/core'

const colors = generateUnoThemeColors()
const tokens = generateUnoThemeTokens()

// ── CSS Variable Key Mapping ────────────────────────────────────────
// Maps each logical "type" to the corresponding --sh-* CSS variable prefix.
// These must match the keys generated by generateBaselineCss() in src/core.
const cssVarMap: Record<string, string> = {
  default: 'text-primary',
  primary: 'primary',
  success: 'status-success',
  warning: 'status-warning',
  danger: 'status-danger',
  info: 'status-info',
}

// ── Helper: generate per-type variant shortcuts ─────────────────────
// Uses arbitrary CSS variable syntax bg-[var(--sh-*)] instead of theme color
// dot-notation (bg-status.danger.fade) which does NOT resolve inside shortcuts.
function variantShortcuts(): Record<string, string> {
  const result: Record<string, string> = {}

  for (const [type, v] of Object.entries(cssVarMap)) {
    // Fill: colored bg + matching text
    result[`sh-fill-${type}`] = [
      `bg-[var(--sh-${v}-fade)]`,
      `text-[var(--sh-${v})]`,
      `border-transparent`,
    ].join(' ')

    // Ghost: transparent bg, colored text, bg on hover
    result[`sh-ghost-${type}`] = [
      `bg-transparent`,
      `text-[var(--sh-${v})]`,
      `border-transparent`,
      `hover:bg-[var(--sh-${v}-fade)]`,
      `active:brightness-80`,
    ].join(' ')

    // Text: no bg or border, colored text only
    result[`sh-text-${type}`] = [
      `bg-transparent`,
      `text-[var(--sh-${v})]`,
      `border-transparent`,
      `hover:text-[var(--sh-${v}-lighten)]`,
    ].join(' ')

    // Outline: transparent bg, solid colored border
    result[`sh-outline-${type}`] = [
      `bg-transparent`,
      `text-[var(--sh-${v})]`,
      `border-[var(--sh-${v})]`,
      `border-solid`,
      `hover:bg-[var(--sh-${v}-fade)]`,
    ].join(' ')

    // Dashed: transparent bg, dashed colored border
    result[`sh-dashed-${type}`] = [
      `bg-transparent`,
      `text-[var(--sh-${v})]`,
      `border-[var(--sh-${v})]`,
      `border-dashed`,
      `hover:bg-[var(--sh-${v}-fade)]`,
    ].join(' ')

    // Bordered: fill bg + colored border
    result[`sh-bordered-${type}`] = [
      `bg-[var(--sh-${v}-fade)]`,
      `text-[var(--sh-${v})]`,
      `border-[var(--sh-${v})]`,
      `border-solid`,
    ].join(' ')
  }

  return result
}

// ── Safelist: all dynamic shortcut combinations ─────────────────────
// Required because UnoCSS cannot statically detect template literal class
// names like `sh-fill-${props.type}`. All generated shortcuts must be listed.
const variantPrefixes = [
  'sh-fill',
  'sh-ghost',
  'sh-text',
  'sh-outline',
  'sh-dashed',
  'sh-bordered',
]
const typeKeys = Object.keys(cssVarMap)
const safelist = [
  ...variantPrefixes.flatMap((p) => typeKeys.map((t) => `${p}-${t}`)),
  'sh-size-sm',
  'sh-size-md',
  'sh-size-lg',
  'sh-interactive',
  'sh-disabled',
]

export default defineConfig({
  transformers: [transformerDirectives(), transformerVariantGroup()],

  safelist,

  shortcuts: {
    // ── Shared Component Variant Shortcuts ─────────────────────────
    ...variantShortcuts(),

    // ── Size Shortcuts (use design tokens) ────────────────────────
    'sh-size-sm':
      'h-[var(--sh-component-size-sm)] text-[var(--sh-font-size-sm)] px-[var(--sh-spacing-sm)]',
    'sh-size-md':
      'h-[var(--sh-component-size-md)] text-[var(--sh-font-size-md)] px-[var(--sh-spacing-md)]',
    'sh-size-lg':
      'h-[var(--sh-component-size-lg)] text-[var(--sh-font-size-lg)] px-[var(--sh-spacing-lg)]',

    // ── Common component base styles ──────────────────────────────
    'sh-interactive': 'cursor-pointer transition-all duration-300 ease-in-out',
    'sh-disabled': 'opacity-60 cursor-not-allowed',
  },

  theme: {
    colors: {
      ...colors,
    },
  },
})
