import { defineConfig } from 'unocss'
import transformerDirectives from '@unocss/transformer-directives'
import transformerVariantGroup from '@unocss/transformer-variant-group'
import { generateUnoThemeColors, generateUnoThemeTokens } from './src/core'

const colors = generateUnoThemeColors()
const tokens = generateUnoThemeTokens()

// ── CSS Variable Key Mapping ────────────────────────────────────────
// Maps each logical "type" to the corresponding --sh-* CSS variable prefix.
// These must match the keys generated by generateBaselineCss() in src/core.
const cssVarMap: Record<string, string> = {
  default: 'text-primary',
  primary: 'primary',
  success: 'status-success',
  warning: 'status-warning',
  danger: 'status-danger',
  info: 'status-info',
}

// ── Safelist: all dynamic shortcut combinations ─────────────────────
// Required because UnoCSS cannot statically detect template literal class
// names like `sh-fill-${props.type}`. All generated shortcuts must be listed.
const variantPrefixes = [
  'sh-fill',
  'sh-ghost',
  'sh-text',
  'sh-outline',
  'sh-dashed',
  'sh-bordered',
]
const typeKeys = Object.keys(cssVarMap)
const radiusKeys = ['none', 'sm', 'md', 'lg', 'xl', 'full']
const safelist = [
  ...variantPrefixes.flatMap((p) => typeKeys.map((t) => `${p}-${t}`)),
  'sh-size-sm',
  'sh-size-md',
  'sh-size-lg',
  'sh-interactive',
  'sh-disabled',
  ...radiusKeys.map((r) => `sh-rounded-${r}`),
]

export default defineConfig({
  transformers: [transformerDirectives(), transformerVariantGroup()],

  safelist,

  shortcuts: [
    // ── Dynamic Variant Shortcuts ────────────────────────────────
    [
      /^sh-(fill|ghost|text|outline|dashed|bordered)-(.*)$/,
      (match) => {
        const [, variant, type] = match
        const v = cssVarMap[type]
        if (!v) return '' // ignore if type not mapped

        switch (variant) {
          case 'fill':
            return `bg-[var(--sh-${v}-fade)] text-[var(--sh-${v})] border-transparent`
          case 'ghost':
            return `bg-transparent text-[var(--sh-${v})] border-transparent hover:bg-[var(--sh-${v}-fade)] active:brightness-80`
          case 'text':
            return `bg-transparent text-[var(--sh-${v})] border-transparent hover:text-[var(--sh-${v}-lighten)]`
          case 'outline':
            return `bg-transparent text-[var(--sh-${v})] border-[color:var(--sh-${v})] border-solid hover:bg-[var(--sh-${v}-fade)]`
          case 'dashed':
            return `bg-transparent text-[var(--sh-${v})] border-[var(--sh-${v})] border-dashed hover:bg-[var(--sh-${v}-fade)]`
          case 'bordered':
            return `bg-[var(--sh-${v}-fade)] text-[var(--sh-${v})] border-[var(--sh-${v})] border-solid`
          default:
            return ''
        }
      },
    ],

    // ── Dynamic Size Shortcuts ──────────────────────────────────
    [
      /^sh-size-(sm|md|lg)$/,
      ([, size]) =>
        `h-[var(--sh-component-size-${size})] text-[var(--sh-font-size-${size})] px-[var(--sh-spacing-${size})]`,
    ],

    // ── Dynamic Radius Shortcuts ──────────────────────────────────
    [
      /^sh-rounded-(none|sm|md|lg|xl|full)$/,
      ([, r]) => `rounded-[length:var(--sh-radius-${r})]`,
    ],

    // ── Common component base styles ──────────────────────────────
    {
      'sh-interactive':
        'cursor-pointer transition-all duration-300 ease-in-out',
      'sh-disabled': 'opacity-60 cursor-not-allowed',
    },
  ],

  theme: {
    colors: {
      ...colors,
    },
    borderRadius: tokens.borderRadius,
    spacing: tokens.spacing,
    fontSize: tokens.fontSize,
  },
})
